### ISSUE TITLE
travis build failed

### ISSUE THREAD

**Issue by jewelnuruddin** [jewelnuruddin/puppet-abrt#4]
It seems all the build is failed because of few reason
 mainly because of ruby version for
example 

**1**

```
SyntaxError: /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/metadata-json-lint-1.2.2/lib/metadata_json_lint.rb:39: unknown type of %string
...on('-f', '--format FORMAT', %i[text json], 'The format in wh...
...                               ^
/home/travis/.rvm/gems/ruby-1.9.3-p551/gems/metadata-json-lint-1.2.2/lib/metadata_json_lint.rb:39: syntax error, unexpected $end, expecting ')'
...on('-f', '--format FORMAT', %i[text json], 'The format in wh...

```
ref: https://github.com/voxpupuli/metadata-json-lint/issues/74

**2**

```
1.38s$ bundle exec rake validate && bundle exec rake lint && bundle exec rake spec SPEC_OPTS='--format documentation'
---> syntax:manifests
Support for ruby version 2.1.5 is deprecated and will be removed in a future release. See https://puppet.com/docs/puppet/latest/system_requirements.html for a list of supported ruby versions.
   (location: /home/travis/.rvm/gems/ruby-2.1.5/gems/puppet-5.5.10/lib/puppet.rb:130:in `<module:Puppet>')

```

**3**

```
$ bundle exec rake validate && bundle exec rake lint && bundle exec rake spec SPEC_OPTS='--format documentation'
---> syntax:manifests
Support for ruby version 2.1.6 is deprecated and will be removed in a future release. See https://puppet.com/docs/puppet/latest/system_requirements.html for a list of supported ruby versions.
(location: /home/travis/.rvm/gems/ruby-2.1.6/gems/puppet-5.5.13/lib/puppet.rb:130:in `<module:Puppet>')
The command "bundle exec rake validate && bundle exec rake lint && bundle exec rake spec SPEC_OPTS='--format documentation'" exited with 1.

```

**Comment by jewelnuruddin** [comment]
Simplified build check with update by ruby version because lots of dependencies problem if we keep all the following versions

```
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 3.6.0"
  - rvm: 2.1.5
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 2.1.5
    env: PUPPET_GEM_VERSION="~> 3.0" FUTURE_PARSER="yes"
  - rvm: 2.1.6
    env: PUPPET_GEM_VERSION="~> 4.0" STRICT_VARIABLES="yes"

```
So just use the following

```
  - rvm: 2.3.7
    env: PUPPET_GEM_VERSION="~> 3.0" FUTURE_PARSER="no"
  - rvm: 2.3.7
    env: PUPPET_GEM_VERSION="~> 4.0" STRICT_VARIABLES="no"
```

**Fixed**
